## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd
import numpy as np

df = pd.DataFrame(data)
print(df, end='\n\n')

job_psychologist = df['job'] == 'psychologist'
num_cars_greater_than_family_size = df['num_cars'] > df['family_size']
print(df[job_psychologist & num_cars_greater_than_family_size], end='\n\n') 

at_most_two_fam = df['family_size'] <= 2
at_least_one_car = df['num_cars'] >= 1
print(df[at_most_two_fam & at_least_one_car], end='\n\n')

print(len(pd.unique(df['job'])))

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here

df = pd.DataFrame(dict(fruit = fruit, weight = weights))
print(df, end='\n\n')

dfBanana = df[df.fruit == 'banana']
dfApple = df[df.fruit == 'apple']
dfCarrot = df[df.fruit == 'carrot']

dfBanana_mean = np.mean(dfBanana)
print('average banana weight = ' + str(dfBanana_mean))

dfApple_mean = np.mean(dfApple)
print('average apple weight = ' + str(dfApple_mean))

dfCarrot_mean = np.mean(dfCarrot)
print('average carrot weight = ' + str(dfCarrot_mean))

    fruit  weight
0  banana     1.0
1  banana     2.0
2  banana     3.0
3   apple     4.0
4   apple     5.0
5  carrot     6.0
6  banana     7.0
7   apple     8.0
8  carrot     9.0
9  banana    10.0

average banana weight = weight    4.6
dtype: float64
average apple weight = weight    5.666667
dtype: float64
average carrot weight = weight    7.5
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here

course_name_lower = []
for e in course_name:
  e_lower = e.lower()
  course_name_lower.append(e_lower)
sort = np.argsort(course_name_lower)
print(sort)

start_with_p = []
for e in course_name:
  for letter in e:
    if letter.lower() == 'p':
      start_with_p.append(e)
    else:
      break
print(start_with_p)

[2 4 1 3 0]
['Python', 'PHP']


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [1]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [8]:
# Type your solution here

print(student_id)
student_id_reverse = np.flip(student_id)
print(student_id_reverse)

student_id_sort = np.sort(student_id)
student_id_sort_reverse = student_id_sort[::-1]
student_id_top_3 = student_id_sort_reverse[0:3]
print(student_id_top_3)

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
[6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [16]:
# Type your solution here

multiple_3 = np.arange(0,100,3)
multiple_5 = np.arange(0,100,5)

sum_3 = np.sum(multiple_3)
sum_5 = np.sum(multiple_5)
total_sum = sum_3 + sum_5 - 30 - 60 - 90 #because these numbers are repeats
print(total_sum)

# Hint: you can use arange to start off

2453


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [30]:
import numpy as np

arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
# Type your solution here

arr1[:,[2,1]] = arr1[:,[1,2]]
print(arr1)

arr2 = np.arange(12).reshape(3,4)
arr2[[1,0],:] = arr2[[0,1],:]
print(arr2)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
